use warehouse gavi_compute_wh;

CREATE OR REPLACE VIEW EMPIRE_DB.SILVER_LAYER.VIP_AGENT_PERFORMANCE AS
SELECT
    Agent_Type_Clean AS Node_Name,
    COUNT(Log_ID) AS Total_Executions,
    SUM(CASE WHEN Final_Status = 'SUCCESS' THEN 1 ELSE 0 END) AS Successful_Runs,
    SUM(CASE WHEN Final_Status = 'FAILED' THEN 1 ELSE 0 END) AS Failed_Runs
FROM EMPIRE_DB.SILVER_LAYER.CLEAN_WORKFLOW_LOGS
GROUP BY Agent_Type_Clean;

ALTER WAREHOUSE GAVI_COMPUTE_WH SUSPEND;